#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/opt/homebrew/share/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/hamza/Desktop/Repos/EmergencyNotificationApp"
export "FLUTTER_FRAMEWORK_SWIFT_PACKAGE_PATH=/Users/hamza/Desktop/Repos/EmergencyNotificationApp/ios/Flutter/ephemeral/Packages/.packages/FlutterFramework"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/hamza/Desktop/Repos/EmergencyNotificationApp/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_DEFINES=RkxVVFRFUl9WRVJTSU9OPTMuNDMuMC0xLjAucHJlLTU2Mg==,RkxVVFRFUl9DSEFOTkVMPW1haW4=,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049Y2JmNTgwMjQzYw==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049Y2JmNTgwMjQzYw==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMy4wIChidWlsZCAzLjEzLjAtNS4wLmRldik="
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/hamza/Desktop/Repos/EmergencyNotificationApp/.dart_tool/package_config.json"
